# Generated by Django 2.2.1 on 2019-05-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70)),
                ('audio', models.FileField(upload_to='tracks/')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('size', models.IntegerField()),
                ('artists', models.ManyToManyField(related_name='tracks', to='main.Artist')),
                ('genre', models.ManyToManyField(related_name='tracks', to='main.Genre')),
            ],
        ),
    ]
