# Generated by Django 2.2.1 on 2019-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190529_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lang',
            field=models.CharField(db_index=True, default='foreign', max_length=10),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
