# Generated by Django 2.2.1 on 2019-05-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190529_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
