# Generated by Django 2.2.1 on 2019-05-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_track_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='text',
            field=models.TextField(blank=True, default='Текст песни пока не добавлен!'),
        ),
    ]
