# Generated by Django 2.2.1 on 2019-05-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190530_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='track',
            name='size',
        ),
    ]
